In [8]:
# Stwórz DataFrame zawierający informacje o 10 produktach w sklepie: nazwa, cena, ilość na
# stanie, kategoria.
# Wymagania:
# Użyj słownika do utworzenia DataFrame
# Wyświetl pierwsze 5 wierszy
# Oblicz całkowitą wartość towaru (cena * ilość) i dodaj jako nową kolumnę
# -> DataFrame z 10 produktami i kolumną 'WartośćCałkowita'


import pandas as pd

produkty = {'nazwa': ['kawa','stolik', 'kubek', 'mleko'],
            'cena': [50,300,30,5],
            'ilosc': [300,8,100,40],
            'kategoria': ['napój', 'mebel', 'zastawa', 'napój']}
frame = pd.DataFrame(produkty)
print(frame)

frame.insert(loc=3,column='wartosc', value= frame.cena * frame.ilosc)
frame.head()

    nazwa  cena  ilosc kategoria
0    kawa    50    300     napój
1  stolik   300      8     mebel
2   kubek    30    100   zastawa
3   mleko     5     40     napój

    nazwa  cena  ilosc  wartosc kategoria
0    kawa    50    300    15000     napój
1  stolik   300      8     2400     mebel
2   kubek    30    100     3000   zastawa
3   mleko     5     40      200     napój

In [42]:
# Wyczyść dataset Titanic stosując pełny pipeline:
# Wymagania:
# Usuń kolumny z >60% NaN
# Wypełnij Age medianą
# Wypełnij Embarked dominantą
# Usuń wiersze z pozostałymi NaN
# Przed i po: wypisz kształt DataFrame
# Sprawdź czy nie ma NaN
# Porównaj rozkład Age przed i po
import pandas as pd

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

titanic = pd.read_csv(url)
print(titanic)

threshold = len(titanic) * 0.6
titanic = titanic.dropna(thresh=threshold,axis=1)

kopia = titanic.copy()
titanic_mediana = kopia['Age'].median()
kopia['Age'] = kopia['Age'].fillna(titanic_mediana)

embarked_mode = kopia['Embarked'].mode()[0] 
kopia['Embarked'] = kopia['Embarked'].fillna(embarked_mode)
print(f"\nEmbarked po wypełnieniu dominantą ('{embarked_mode}'):")
print(kopia['Embarked'].value_counts())

kopia.dropna(axis='rows').head()

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

Embarked po wypełnieniu dominantą ('S'):
Embarked
S    646
C    168
Q     77
Name: count, dtype: int64

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [54]:
# Stwórz nowe zmienne z Titanic:
# Wymagania:
# FamilySize = SibSp + Parch + 1
# IsAlone = 1 jeśli FamilySize == 1, inaczej 0
# AgeGroup = kategorie (0-12, 13-18, 19-35, 36-60, 60+)
# Dodaj wszystkie 3 zmienne do DataFrame
# Wyświetl value_counts() dla każdej
# Oblicz wskaźnik przeżycia dla IsAlone vs nie alone

import pandas as pd

url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

titanic = pd.read_csv(url)
titanic_clean = titanic.copy()
print(titanic_clean)

titanic_clean['FamilySize'] = titanic_clean['SibSp'] + titanic_clean['Parch'] + 1
print(titanic_clean['FamilySize'].value_counts().head())

titanic_clean['IsAlone'] = (titanic_clean['FamilySize'] == 1).astype(int)
print(f"\nPasażerowie samotni: {titanic_clean['IsAlone'].sum()}")

przedzial_wiekowy = [0, 12, 18, 35, 60, 120]
kat = ['Dziecko', 'Nastolatek', 'Dorosły', 'Starszy', 'Senior']
titanic_clean["AgeGroup"] = pd.cut(titanic_clean['Age'], bins=przedzial_wiekowy, labels=kat)
print(titanic_clean['AgeGroup'].value_counts())

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]
FamilySize
1    537
2    161
3    102
4     29
6     22
Name: count, dtype: int64

Pasażerowie samotni: 537
AgeGroup
Dorosły       358
Starszy       195
Nastolatek     70
Dziecko        69
Senior         22
Name: count, dtype: int64